# Generated by Django 4.1 on 2022-10-18 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_category', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Website Design', 'Website Design'), ('App Development', 'App Development'), ('Quality Assurance', 'Quality Assurance'), ('Development', 'Development'), ('Backend Development', 'Backend Development'), ('Software Testing', 'Software Testing'), ('Marketing', 'Marketing'), ('SEO', 'SEO'), ('Other', 'Other')], default='Other', max_length=255)),
                ('is_ongoing', models.BooleanField(default=True)),
                ('description', models.TextField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Todo', 'Todo'), ('In Development', 'In Development'), ('Completed', 'Completed'), ('Approval', 'Approval')], max_length=255, null=True)),
                ('priority', models.CharField(choices=[('Highest', 'Highest'), ('Lowest', 'Lowest'), ('Medium', 'Medium')], default='Lowest', max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.departments')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('task_category', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Website Design', 'Website Design'), ('App Development', 'App Development'), ('Quality Assurance', 'Quality Assurance'), ('Development', 'Development'), ('Backend Development', 'Backend Development'), ('Software Testing', 'Software Testing'), ('Marketing', 'Marketing'), ('SEO', 'SEO'), ('Other', 'Other')], default='Other', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Highest', 'Highest'), ('Lowest', 'Lowest'), ('Medium', 'Medium')], default='Lowest', max_length=255)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Todo', 'Todo'), ('In Development', 'In Development'), ('Completed', 'Completed'), ('Approval', 'Approval')], max_length=255, null=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('in_review', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task_created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projects')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.DateTimeField()),
                ('assigned_to', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.projects')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.task')),
            ],
        ),
    ]
