# Generated by Django 4.1 on 2022-10-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='started',
        ),
        migrations.AddField(
            model_name='projects',
            name='is_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projects',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
