# Generated by Django 4.1 on 2022-10-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_projects_approval_remove_projects_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='need_review',
            field=models.BooleanField(default=True),
        ),
    ]
