# Generated by Django 4.1 on 2022-10-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_projecticons_alter_projects_icons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='icons',
        ),
    ]
