# Generated by Django 4.1 on 2022-10-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_in_progress_task_need_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='need_review',
            field=models.BooleanField(default=False),
        ),
    ]
