# Generated by Django 4.1 on 2022-10-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_projects_icons'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='icons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.projecticons'),
        ),
    ]
