# Generated by Django 4.1 on 2022-10-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_task_need_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='need_review',
            new_name='in_review',
        ),
    ]
