# Generated by Django 4.1 on 2022-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_projects_icons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecticons',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
