# Generated by Django 4.1 on 2022-10-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_need_review_task_in_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project',
            new_name='project_name',
        ),
    ]
