# Generated by Django 4.1 on 2022-10-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_project_projects_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
