# Generated by Django 4.1 on 2022-10-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_projecticons_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='icons',
        ),
        migrations.DeleteModel(
            name='ProjectIcons',
        ),
    ]
