# Generated by Django 4.1 on 2022-10-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_projects_created_at_alter_projects_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='priority',
            field=models.CharField(choices=[('HIGHEST', 'Highest'), ('LOWEST', 'Lowest'), ('MEDIUM', 'Medium')], default='Lowest', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
