# Generated by Django 4.1 on 2022-10-18 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='members',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='updated_at',
        ),
    ]
